version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "88:80" # Map port 8080 di host ke port 80 di container
    volumes:
      - .:/app # Optional: Mount source code for development (reflects changes)
      - /app/node_modules # Optional: Don't mount node_modules from host
    environment:
      - NODE_ENV=development # Atau production, sesuai kebutuhan
    # Untuk Vite, Anda mungkin perlu memastikan dev server berjalan di host 0.0.0.0
    # command: yarn dev --host